### ISSUE TITLE
为啥文件地址会在fakepath文件夹？

### ISSUE THREAD

**Issue by stevejobschen** [ztyzbb/WOT-Tank-Information-Creater#1]
上传时显示
![image](https://user-images.githubusercontent.com/22467932/27996026-87ed1918-650b-11e7-902c-4a88c3e70fe9.png)
然后文件地址会在
![image](https://user-images.githubusercontent.com/22467932/27996034-9351086e-650b-11e7-812e-88088cb78664.png)

**Comment by ztyzbb** [comment]
您好，这个问题我已经转交给网站的管理员了，不过fakepath是正常的，我自己上传也是这个。这个错误应该是指您上传的文件本身有错或者上传过程中出现了错误，您可以先试试能否用客户端播放它，如果可以，则再次上传，如果还不行，则有可能是网站的解析程序的确有Bug，您可以加QQ群156374046，群主会帮您解决，或者留下联系方式由我帮您转交，谢谢！

**Comment by ztyzbb** [comment]
刚才管理员回复我了，您上传的可能是一个中途退出的录像，这种录像是没有战斗结算数据的，所以暂时不能上传

**Comment by stevejobschen** [comment]
好吧，感谢回复。
